#pragma once

#define IDR_MAINMENU         128
#define IDR_PROC_MENU        129

#define IDC_NAV              1001
#define IDC_NAV_SEP          1026
#define IDC_PROCLIST         1002
#define IDC_PERF_FRAME       1003
#define IDC_CPU_LABEL        1004
#define IDC_CPU_BAR          1005
#define IDC_MEM_LABEL        1006
#define IDC_MEM_BAR          1007
#define IDC_SPEED_LABEL      1008
#define IDC_CPU_GRAPH        1009
#define IDC_MEM_GRAPH        1010
#define IDC_MEM_DETAILS      1011
#define IDC_CPU_TITLE        1013
#define IDC_CPU_MODEL        1014
#define IDC_CPU_STATS_L      1015
#define IDC_CPU_STATS_R      1016
#define IDC_CPU_LIVE_LBL     1020
#define IDC_CPU_LIVE_VAL     1021
#define IDC_CPU_STAT_SEP     1022
#define IDC_CPU_SPEC_LBL     1023
#define IDC_CPU_SPEC_VAL     1024
#define IDC_CPU_GRAPH_SUB    1025
#define IDC_CPU_STATS_PANEL  1027
#define IDC_MEM_TITLE        1017
#define IDC_MEM_MODEL        1033
#define IDC_MEM_GRAPH_SUB    1034
#define IDC_MEM_COMP_SUB     1035
#define IDC_MEM_COMP_GRAPH   1036
#define IDC_MEM_STATS_PANEL  1037
#define IDC_ENDTASK_BTN      1038
#define IDC_NET_TITLE        1039
#define IDC_NET_SUB          1040
#define IDC_NET_GRAPH        1041
#define IDC_MAIN_TAB         1018
#define IDC_STUB             1019
#define IDM_ENDTASK          2001
#define ID_FILE_EXIT         40001
#define ID_VIEW_REFRESH      40002
#define ID_OPTIONS_TOPMOST   40003
#define ID_VIEW_CPU_GRAPH_OVERALL 40004
#define ID_VIEW_CPU_GRAPH_PERCPU   40005

#define IDS_APP_TITLE        1
#define IDS_NAV_PROCESSES    2
#define IDS_NAV_CPU          3
#define IDS_NAV_MEMORY       15
#define IDS_COL_NAME         4
#define IDS_COL_PID          5
#define IDS_COL_CPU          6
#define IDS_COL_MEM          7
#define IDS_COL_STATUS       119
#define IDS_COL_DISK         120
#define IDS_COL_NETWORK      121
#define IDS_CPU_USAGE        8
#define IDS_MEM_USAGE        9
#define IDS_BASE_SPEED       10
#define IDS_SPEED_UNKNOWN    11
#define IDS_ENDTASK          12
#define IDS_ENDTASK_WARN     13
#define IDS_ERR_OPEN         14
#define IDS_MEM_PHYS_TOTAL   16
#define IDS_MEM_PHYS_AVAIL   17
#define IDS_MEM_COMMIT       18
#define IDS_NAV_TASK_HINT    19
#define IDS_STAT_UTIL        20
#define IDS_STAT_SPEED       21
#define IDS_STAT_PROCS       22
#define IDS_STAT_THREADS     23
#define IDS_STAT_HANDLES     24
#define IDS_STAT_UPTIME      25
#define IDS_SPEC_SOCKETS     26
#define IDS_SPEC_LOGICAL     27
#define IDS_PANEL_CPU        28
#define IDS_PANEL_MEMORY     29
#define IDS_TAB_PERFORMANCE  30
#define IDS_TAB_APPHISTORY   31
#define IDS_TAB_STARTUP      32
#define IDS_TAB_USERS        33
#define IDS_TAB_DETAILS      34
#define IDS_TAB_SERVICES     35
#define IDS_STUB_BODY        36
#define IDS_GRAPH_SCALE      37
#define IDS_GRAPH_CAPTION    38
#define IDS_GRAPH_MEMCAP     39
#define IDS_GRAPH_CAPTION_PERCPU 52
#define IDS_VIEW_CPU_GRAPH   53
#define IDS_VIEW_CPU_OVERALL 54
#define IDS_VIEW_CPU_PERLOG  55
#define IDS_CPU_N_LABEL      56
#define IDS_CPU_UTIL_60S     57
#define IDS_LBL_UTIL         58
#define IDS_LBL_SPEED        59
#define IDS_LBL_PROCS        60
#define IDS_LBL_THREADS      61
#define IDS_LBL_HANDLES      62
#define IDS_LBL_UPTIME       63
#define IDS_LBL_BASE         64
#define IDS_LBL_SOCKETS      65
#define IDS_LBL_CORES        66
#define IDS_LBL_LOGICAL      67
#define IDS_LBL_VIRT         68
#define IDS_LBL_L2           69
#define IDS_LBL_L3           70
#define IDS_LBL_L1           71
#define IDS_SPEC_CORES       40
#define IDS_SPEC_VIRT        41
#define IDS_VIRT_ENABLED     42
#define IDS_VIRT_DISABLED    43
#define IDS_SPEC_L2          44
#define IDS_SPEC_L3          45
#define IDS_CACHE_KB         46
#define IDS_VIRT_UNKNOWN     51
#define IDS_ENDTASK_SELF     106
#define IDS_MEM_GRAPH_60S    107
#define IDS_MEM_COMPOSITION  108
#define IDS_MEM_LBL_INUSE    109
#define IDS_MEM_LBL_COMMIT   110
#define IDS_MEM_LBL_PAGED    111
#define IDS_MEM_LBL_AVAIL    112
#define IDS_MEM_LBL_CACHED   113
#define IDS_MEM_LBL_NONPAGED 114
#define IDS_MEM_LBL_SPEED    115
#define IDS_MEM_LBL_SLOTS    116
#define IDS_MEM_LBL_FORM     117
#define IDS_MEM_LBL_HWRES    118
#define IDS_NET_THROUGHPUT   129
