#include "precomp.h"
#include "acpi_new.h"

static
PACPI_NEW_PDO_EXTENSION
AcpiNewFindPdoByNodeLocked(
    _In_ PACPI_NEW_FDO_EXTENSION FdoExt,
    _In_ uacpi_namespace_node *Node)
{
    PLIST_ENTRY entry;
    for (entry = FdoExt->PdoList.Flink; entry != &FdoExt->PdoList; entry = entry->Flink)
    {
        PACPI_NEW_PDO_EXTENSION pdoExt = CONTAINING_RECORD(entry, ACPI_NEW_PDO_EXTENSION, Link);
        if (pdoExt->Node == Node)
            return pdoExt;
    }
    return NULL;
}

static
VOID
AcpiNewUpdatePdoPresenceLocked(_In_ PACPI_NEW_FDO_EXTENSION FdoExt)
{
    PLIST_ENTRY entry;
    for (entry = FdoExt->PdoList.Flink; entry != &FdoExt->PdoList; entry = entry->Flink)
    {
        PACPI_NEW_PDO_EXTENSION pdoExt = CONTAINING_RECORD(entry, ACPI_NEW_PDO_EXTENSION, Link);
        uacpi_u32 sta = 0;
        uacpi_status st;

        if (!pdoExt->Node)
            continue;

        st = uacpi_eval_sta(pdoExt->Node, &sta);
        if (uacpi_unlikely_error(st))
            continue;

        pdoExt->StaFlags = sta;
        pdoExt->Present = ((sta & 0x1) != 0);
    }
}

static
NTSTATUS
AcpiNewCreatePdo(
    _In_ PDRIVER_OBJECT DriverObject,
    _In_ PACPI_NEW_FDO_EXTENSION FdoExt,
    _In_ uacpi_namespace_node *Node,
    _In_z_ const uacpi_char *Hid,
    _In_ uacpi_u32 StaFlags)
{
    NTSTATUS status;
    PDEVICE_OBJECT pdo;
    PACPI_NEW_PDO_EXTENSION pdoExt;

    status = IoCreateDevice(DriverObject,
                            sizeof(ACPI_NEW_PDO_EXTENSION),
                            NULL,
                            FILE_DEVICE_CONTROLLER,
                            FILE_AUTOGENERATED_DEVICE_NAME,
                            FALSE,
                            &pdo);
    if (!NT_SUCCESS(status))
        return status;

    pdoExt = (PACPI_NEW_PDO_EXTENSION)pdo->DeviceExtension;
    RtlZeroMemory(pdoExt, sizeof(*pdoExt));
    pdoExt->Common.Type = AcpiNewDevicePdo;
    pdoExt->Common.Self = pdo;
    pdoExt->ParentFdo = FdoExt->Common.Self;
    pdoExt->Node = Node;
    pdoExt->StaFlags = StaFlags;
    pdoExt->Present = TRUE;

    ExInitializeFastMutex(&pdoExt->NotifyLock);
    InitializeListHead(&pdoExt->NotifyList);

    status = AcpiNewBuildIdsFromHid(Hid, &pdoExt->DeviceId, &pdoExt->HardwareIds);
    if (!NT_SUCCESS(status))
    {
        IoDeleteDevice(pdo);
        return status;
    }

    (void)AcpiNewBuildCompatibleIdsFromCid(Node, &pdoExt->CompatibleIds);

    {
        uacpi_id_string *uid = NULL;
        uacpi_status st;
        st = uacpi_eval_uid(Node, &uid);
        if (!uacpi_unlikely_error(st) && uid && uid->value)
        {
            ANSI_STRING ansi;
            UNICODE_STRING uni;
            RtlInitAnsiString(&ansi, uid->value);
            if (NT_SUCCESS(RtlAnsiStringToUnicodeString(&uni, &ansi, TRUE)))
            {
                pdoExt->InstanceId = AcpiNewDupUnicodeString(uni.Buffer, uni.Length / sizeof(WCHAR));
                RtlFreeUnicodeString(&uni);
            }
        }
        if (uid)
            uacpi_free_id_string(uid);
    }

    pdo->Flags |= DO_POWER_PAGABLE;
    pdo->Flags &= ~DO_DEVICE_INITIALIZING;

    ExAcquireFastMutex(&FdoExt->Mutex);
    InsertTailList(&FdoExt->PdoList, &pdoExt->Link);
    ExReleaseFastMutex(&FdoExt->Mutex);

    return STATUS_SUCCESS;
}

static
uacpi_iteration_decision
AcpiNewEnumCallback(
    _In_ void *User,
    _In_ uacpi_namespace_node *Node,
    _In_ uacpi_u32 NodeDepth)
{
    PACPI_NEW_FDO_EXTENSION fdoExt = (PACPI_NEW_FDO_EXTENSION)User;
    uacpi_namespace_node_info *info = NULL;
    uacpi_status st;
    uacpi_u32 sta = 0;
    PACPI_NEW_PDO_EXTENSION existing;

    UNREFERENCED_PARAMETER(NodeDepth);

    if (uacpi_namespace_node_is_alias(Node))
        return UACPI_ITERATION_DECISION_CONTINUE;

    st = uacpi_eval_sta(Node, &sta);
    if (uacpi_unlikely_error(st))
        return UACPI_ITERATION_DECISION_CONTINUE;

    if ((sta & 0x1) == 0)
        return UACPI_ITERATION_DECISION_CONTINUE;

    st = uacpi_get_namespace_node_info(Node, &info);
    if (uacpi_unlikely_error(st) || !info)
        return UACPI_ITERATION_DECISION_CONTINUE;

    if (!(info->flags & UACPI_NS_NODE_INFO_HAS_HID) || !info->hid.value)
    {
        uacpi_free_namespace_node_info(info);
        return UACPI_ITERATION_DECISION_CONTINUE;
    }

    ExAcquireFastMutex(&fdoExt->Mutex);
    existing = AcpiNewFindPdoByNodeLocked(fdoExt, Node);
    if (existing)
    {
        existing->StaFlags = sta;
        existing->Present = TRUE;
        ExReleaseFastMutex(&fdoExt->Mutex);
    }
    else
    {
        ExReleaseFastMutex(&fdoExt->Mutex);
        (void)AcpiNewCreatePdo(fdoExt->Common.Self->DriverObject, fdoExt, Node, info->hid.value, sta);
    }

    uacpi_free_namespace_node_info(info);
    return UACPI_ITERATION_DECISION_CONTINUE;
}

VOID
AcpiNewEnumerateNamespace(_In_ PACPI_NEW_FDO_EXTENSION FdoExt)
{
    uacpi_namespace_node *start;
    uacpi_status st;

    start = uacpi_namespace_get_predefined(UACPI_PREDEFINED_NAMESPACE_SB);
    if (!start)
        start = uacpi_namespace_root();

    st = uacpi_namespace_for_each_child(
        start,
        AcpiNewEnumCallback,
        NULL,
        UACPI_OBJECT_DEVICE_BIT,
        UACPI_MAX_DEPTH_ANY,
        FdoExt
    );

    if (uacpi_unlikely_error(st))
        DPRINT1("uacpi_namespace_for_each_child failed: %s\n", uacpi_status_to_string(st));
}

VOID
AcpiNewRefreshEnumeration(_In_ PACPI_NEW_FDO_EXTENSION FdoExt)
{
    if (!FdoExt->Started)
        return;

    if (InterlockedCompareExchange(&FdoExt->RefreshInProgress, 1, 0) != 0)
        return;

    ExAcquireFastMutex(&FdoExt->Mutex);
    AcpiNewUpdatePdoPresenceLocked(FdoExt);
    ExReleaseFastMutex(&FdoExt->Mutex);

    AcpiNewEnumerateNamespace(FdoExt);

    InterlockedExchange(&FdoExt->RefreshInProgress, 0);
}
