#include "precomp.h"
#include "acpi_new.h"

static
PACPI_NEW_PDO_EXTENSION
AcpiNewFindPdoByNodeLocked(
    _In_ PACPI_NEW_FDO_EXTENSION FdoExt,
    _In_ uacpi_namespace_node *Node)
{
    PLIST_ENTRY entry;
    for (entry = FdoExt->PdoList.Flink; entry != &FdoExt->PdoList; entry = entry->Flink)
    {
        PACPI_NEW_PDO_EXTENSION pdoExt = CONTAINING_RECORD(entry, ACPI_NEW_PDO_EXTENSION, Link);
        if (pdoExt->Node == Node)
            return pdoExt;
    }
    return NULL;
}

static
VOID
AcpiNewUpdatePdoPresenceLocked(_In_ PACPI_NEW_FDO_EXTENSION FdoExt)
{
    PLIST_ENTRY entry;
    for (entry = FdoExt->PdoList.Flink; entry != &FdoExt->PdoList; entry = entry->Flink)
    {
        PACPI_NEW_PDO_EXTENSION pdoExt = CONTAINING_RECORD(entry, ACPI_NEW_PDO_EXTENSION, Link);
        uacpi_u32 sta = 0;
        uacpi_status st;

        if (!pdoExt->Node)
            continue;

        st = uacpi_eval_sta(pdoExt->Node, &sta);
        if (uacpi_unlikely_error(st))
            continue;

        pdoExt->StaFlags = sta;
        pdoExt->Present = ((sta & 0x1) != 0);
    }
}

static
NTSTATUS
AcpiNewCreatePdo(
    _In_ PDRIVER_OBJECT DriverObject,
    _In_ PACPI_NEW_FDO_EXTENSION FdoExt,
    _In_ uacpi_namespace_node *Node,
    _In_z_ const uacpi_char *Hid,
    _In_ uacpi_u32 StaFlags)
{
    NTSTATUS status;
    PDEVICE_OBJECT pdo;
    PACPI_NEW_PDO_EXTENSION pdoExt;

    status = IoCreateDevice(DriverObject,
                            sizeof(ACPI_NEW_PDO_EXTENSION),
                            NULL,
                            FILE_DEVICE_CONTROLLER,
                            FILE_AUTOGENERATED_DEVICE_NAME,
                            FALSE,
                            &pdo);
    if (!NT_SUCCESS(status))
        return status;

    pdoExt = (PACPI_NEW_PDO_EXTENSION)pdo->DeviceExtension;
    RtlZeroMemory(pdoExt, sizeof(*pdoExt));
    pdoExt->Common.Type = AcpiNewDevicePdo;
    pdoExt->Common.Self = pdo;
    pdoExt->ParentFdo = FdoExt->Common.Self;
    pdoExt->Node = Node;
    pdoExt->StaFlags = StaFlags;
    pdoExt->Present = TRUE;

    ExInitializeFastMutex(&pdoExt->NotifyLock);
    InitializeListHead(&pdoExt->NotifyList);

    status = AcpiNewBuildIdsFromHid(Hid, &pdoExt->DeviceId, &pdoExt->HardwareIds);
    if (!NT_SUCCESS(status))
    {
        IoDeleteDevice(pdo);
        return status;
    }

    (void)AcpiNewBuildCompatibleIdsFromCid(Node, &pdoExt->CompatibleIds);

    {
        uacpi_id_string *uid = NULL;
        uacpi_status st;
        st = uacpi_eval_uid(Node, &uid);
        if (!uacpi_unlikely_error(st) && uid && uid->value)
        {
            ANSI_STRING ansi;
            UNICODE_STRING uni;
            RtlInitAnsiString(&ansi, uid->value);
            if (NT_SUCCESS(RtlAnsiStringToUnicodeString(&uni, &ansi, TRUE)))
            {
                pdoExt->InstanceId = AcpiNewDupUnicodeString(uni.Buffer, uni.Length / sizeof(WCHAR));
                RtlFreeUnicodeString(&uni);
            }
        }
        if (uid)
            uacpi_free_id_string(uid);
    }

    /*
     * Some object types (notably Processor() and ThermalZone()) commonly lack _UID.
     * If we don't provide a stable instance ID, PnP can treat multiple objects as
     * the same instance and bugcheck on duplicates.
     */
    if (!pdoExt->InstanceId)
    {
        const uacpi_char *absPath = uacpi_namespace_node_generate_absolute_path(Node);
        if (absPath)
        {
            ANSI_STRING ansi;
            UNICODE_STRING uni;
            SIZE_T uniChars;
            SIZE_T outChars;
            SIZE_T i;

            RtlInitAnsiString(&ansi, absPath);
            if (NT_SUCCESS(RtlAnsiStringToUnicodeString(&uni, &ansi, TRUE)))
            {
                /* Sanitize to something that won't contain path separators. */
                uniChars = (uni.Length / sizeof(WCHAR));
                outChars = 0;

                for (i = 0; i < uniChars; i++)
                {
                    WCHAR ch;
                    ch = uni.Buffer[i];
                    if (ch == L'\\')
                        continue;
                    outChars++;
                }

                if (outChars != 0)
                {
                    PWSTR tmp = (PWSTR)ExAllocatePoolWithTag(PagedPool, (outChars + 1) * sizeof(WCHAR), 'dAcu');
                    if (tmp)
                    {
                        SIZE_T j;
                        j = 0;

                        for (i = 0; i < uniChars; i++)
                        {
                            WCHAR ch;
                            ch = uni.Buffer[i];
                            if (ch == L'\\')
                                continue;

                            if ((ch >= L'0' && ch <= L'9') ||
                                (ch >= L'A' && ch <= L'Z') ||
                                (ch >= L'a' && ch <= L'z') ||
                                (ch == L'_'))
                            {
                                tmp[j++] = ch;
                            }
                            else
                            {
                                tmp[j++] = L'_';
                            }
                        }
                        tmp[j] = UNICODE_NULL;
                        pdoExt->InstanceId = tmp;
                    }
                }

                RtlFreeUnicodeString(&uni);
            }

            uacpi_free_absolute_path(absPath);
        }
    }

    pdo->Flags |= DO_POWER_PAGABLE;
    pdo->Flags &= ~DO_DEVICE_INITIALIZING;

    ExAcquireFastMutex(&FdoExt->Mutex);
    InsertTailList(&FdoExt->PdoList, &pdoExt->Link);
    ExReleaseFastMutex(&FdoExt->Mutex);

    return STATUS_SUCCESS;
}

static
uacpi_iteration_decision
AcpiNewEnumCallback(
    _In_ void *User,
    _In_ uacpi_namespace_node *Node,
    _In_ uacpi_u32 NodeDepth)
{
    PACPI_NEW_FDO_EXTENSION fdoExt = (PACPI_NEW_FDO_EXTENSION)User;
    uacpi_namespace_node_info *info = NULL;
    uacpi_status st;
    uacpi_object_type nodeType;
    uacpi_u32 sta = 0;
    const uacpi_char *hid = NULL;
    PACPI_NEW_PDO_EXTENSION existing;

    UNREFERENCED_PARAMETER(NodeDepth);

    if (uacpi_namespace_node_is_alias(Node))
        return UACPI_ITERATION_DECISION_CONTINUE;

    st = uacpi_namespace_node_type(Node, &nodeType);
    if (uacpi_unlikely_error(st))
        return UACPI_ITERATION_DECISION_CONTINUE;

    if (nodeType != UACPI_OBJECT_DEVICE &&
        nodeType != UACPI_OBJECT_PROCESSOR &&
        nodeType != UACPI_OBJECT_THERMAL_ZONE)
        return UACPI_ITERATION_DECISION_CONTINUE;

    if (nodeType == UACPI_OBJECT_DEVICE)
    {
        st = uacpi_eval_sta(Node, &sta);
        if (uacpi_unlikely_error(st))
            return UACPI_ITERATION_DECISION_CONTINUE;

        if ((sta & 0x1) == 0)
            return UACPI_ITERATION_DECISION_CONTINUE;

        st = uacpi_get_namespace_node_info(Node, &info);
        if (uacpi_unlikely_error(st) || !info)
            return UACPI_ITERATION_DECISION_CONTINUE;

        if (!(info->flags & UACPI_NS_NODE_INFO_HAS_HID) || !info->hid.value)
        {
            uacpi_free_namespace_node_info(info);
            return UACPI_ITERATION_DECISION_CONTINUE;
        }

        hid = info->hid.value;
    }
    else
    {
        /* Processor/ThermalZone objects generally don't have an _HID. */
        sta = 0x1;
        hid = (nodeType == UACPI_OBJECT_PROCESSOR) ? "Processor" : "ThermalZone";
    }

    ExAcquireFastMutex(&fdoExt->Mutex);
    existing = AcpiNewFindPdoByNodeLocked(fdoExt, Node);
    if (existing)
    {
        existing->StaFlags = sta;
        existing->Present = TRUE;
        ExReleaseFastMutex(&fdoExt->Mutex);
    }
    else
    {
        ExReleaseFastMutex(&fdoExt->Mutex);
        (void)AcpiNewCreatePdo(fdoExt->Common.Self->DriverObject, fdoExt, Node, hid, sta);
    }

    if (info)
        uacpi_free_namespace_node_info(info);
    return UACPI_ITERATION_DECISION_CONTINUE;
}

VOID
AcpiNewEnumerateNamespace(_In_ PACPI_NEW_FDO_EXTENSION FdoExt)
{
    uacpi_namespace_node *sb;
    uacpi_namespace_node *tz;
    uacpi_namespace_node *pr;
    uacpi_namespace_node *starts[3];
    uacpi_status st;

    sb = uacpi_namespace_get_predefined(UACPI_PREDEFINED_NAMESPACE_SB);
    if (!sb)
        sb = uacpi_namespace_root();

    tz = uacpi_namespace_get_predefined(UACPI_PREDEFINED_NAMESPACE_TZ);
    pr = uacpi_namespace_get_predefined(UACPI_PREDEFINED_NAMESPACE_PR);

    starts[0] = sb;
    starts[1] = tz;
    starts[2] = pr;

    for (ULONG i = 0; i < RTL_NUMBER_OF(starts); i++)
    {
        if (!starts[i])
            continue;

        st = uacpi_namespace_for_each_child(
            starts[i],
            AcpiNewEnumCallback,
            NULL,
            UACPI_OBJECT_DEVICE_BIT | UACPI_OBJECT_PROCESSOR_BIT | UACPI_OBJECT_THERMAL_ZONE_BIT,
            UACPI_MAX_DEPTH_ANY,
            FdoExt
        );

        if (uacpi_unlikely_error(st))
            DPRINT1("uacpi_namespace_for_each_child failed: %s\n", uacpi_status_to_string(st));
    }
}

VOID
AcpiNewRefreshEnumeration(_In_ PACPI_NEW_FDO_EXTENSION FdoExt)
{
    if (!FdoExt->Started)
        return;

    if (InterlockedCompareExchange(&FdoExt->RefreshInProgress, 1, 0) != 0)
        return;

    ExAcquireFastMutex(&FdoExt->Mutex);
    AcpiNewUpdatePdoPresenceLocked(FdoExt);
    ExReleaseFastMutex(&FdoExt->Mutex);

    AcpiNewEnumerateNamespace(FdoExt);

    InterlockedExchange(&FdoExt->RefreshInProgress, 0);
}
