add_subdirectory(common)
add_subdirectory(targets)
add_subdirectory(hw)
add_subdirectory(control)
add_subdirectory(glyph)
add_subdirectory(sw)
add_subdirectory(meta)
add_subdirectory(api)
add_subdirectory(geometry)
add_subdirectory(uce)
add_subdirectory(resources)
add_subdirectory(fxjit)
add_subdirectory(dll)
